#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to install NGINX web server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/not_found.html
server_block=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
	add_header X-Served-By \$hostname;
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /not_found.html;
        location /not_found.html {
                internal;
        }
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
"
echo "$server_block" > /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx reload
