#!/usr/bin/env bash
#Install and configure HAproxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*
sudo cp /etc/haproxy/haproxy.cfg{,.real}
echo "ENABLED=1" >> /etc/default/haproxy
conf=\
"frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 67011-web-01 100.25.211.130:80 check
        server 67011-web-02 3.90.84.139:80 check"

echo "$conf" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
