#!/usr/bin/env bash
#Install and configure HAproxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*
sudo chown -R ubuntu /etc/haproxy
sudo cp /etc/haproxy/haproxy.cfg{,.real}
echo "ENABLED=1" >> /etc/default/haproxy
conf=\
"frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
	no option http-use-htx
        server 67011-web-01 100.25.194.46:80 check
        server 67011-web-02 100.25.194.197:80 check"

echo "$conf" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
