#!/usr/bin/env bash
#find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo apt-get -y update
sudo apt-get install -y nginx
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
service nginx restart
