#!/usr/bin/env bash
#find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo apt-get update
sudo apt-get install nginx
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
service nginx start
