#!/usr/bin/env bash
#Displays numbers from 1 to 100.
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#Displays in a list format

in="1"
while [ $in -le 100 ]
do
    if [ $((in % 3)) == 0 ] && [ $((in % 5)) == 0 ]
	then echo "FizzBuzz"
    elif [ $((in % 3)) == 0 ]
	then echo "Fizz"
    elif [ $((in % 5)) == 0 ]
	then echo "Buzz"
    else
	echo $in
    fi
    ((in++))
done
