#!/usr/bin/env bash
#Loops from 1 to 10:
#Displays "bad luck" for the 4th iteration
#Displays "good luck" for the 8th iteration
#Displays "Best School" for all other iterations

x=0
while [ $x -lt 10 ]
do
  if [ $x -eq 3 ]
  then
    echo "bad luck"
  elif [ $x -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  x=$((x+1))
done
