#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes:
h="0"
min="1"
while [ $h -le 12 ]
do
	echo "H: $h"
	while [ $min -le 59 ]
	do
	    echo $min
	    min=$((min+1))
	done
	h=$((h+1))
	min="1"
done
